# Generated by Django 5.1.7 on 2025-04-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyimage',
            name='denomination',
            field=models.CharField(choices=[('100', '100 Rupee Note'), ('200', '200 Rupee Note'), ('500', '500 Rupee Note')], default='100', max_length=3),
        ),
        migrations.AddField(
            model_name='currencyimage',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencyimage',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currencyimage',
            name='detection_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyimage',
            name='features_detected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currencyimage',
            name='image',
            field=models.ImageField(upload_to='currency_images/'),
        ),
        migrations.AlterField(
            model_name='currencyimage',
            name='is_authentic',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
